### ISSUE TITLE
Add converter to mesh code.

### ISSUE THREAD

**Issue by otoani** [otoani/rmcc#2]
### Overview
The converter convert latitude and longitude to a regional mesh code.

```python
def convert2MeshCode(lat, lon): 
# convert process.
return meshCode
```

### Tasks

- [ ] coding`convert2MeshCode` method.
- [ ]  test `convert2MeshCode` method.
- [ ]  update PyPI detail in pyproject.toml
- [ ]  increment version.
